default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bvl_store_development
  
test:
  <<: *default
  database: bvl_store_test
  
production:
  <<: *default
  database: bvl_store_production
